export const simulations=[
 {id:'parabola',topic:'functions',title:'Parabola shuffle',subtitle:'Change the stretch and slide the turning point.',predict:'What happens to the opening when a becomes negative?',a:['Coefficient a',-3,3,.25,1,''],b:['Horizontal shift p',-5,5,.5,0,''],assumption:'x from −8 to 8, y from −8 to 8. Curves may continue outside the displayed window.'},
 {id:'tangent',topic:'calculus',title:'Catch the tangent',subtitle:'A straight line with a very local job.',predict:'How does the tangent gradient change as its contact point crosses x = 0?',a:['Contact x',-4,4,.25,1,''],b:['Parabola coefficient a',.25,2,.25,1,''],assumption:'x from −6 to 6, y from −6 to 12. The tangent matches the parabola only at the chosen contact point.'},
 {id:'sine',topic:'trigonometry',title:'Wave hello',subtitle:'Amplitude and period, in one moving picture.',predict:'If b doubles, does the period double or halve?',a:['Amplitude a',.5,4,.25,1,''],b:['Frequency coefficient b',.5,3,.25,1,''],assumption:'x from 0° to 720°, y from −5 to 5; angles are in degrees.'},
 {id:'line',topic:'analytical',title:'Slope safari',subtitle:'Tilt a line and move its intercept.',predict:'What happens to the direction of the line when its gradient is negative?',a:['Gradient m',-3,3,.25,1,''],b:['Intercept c',-5,5,.5,0,''],assumption:'x and y from −8 to 8. A vertical line cannot be written as y = mx + c.'},
 {id:'circle',topic:'analytical',title:'Circle of trust',subtitle:'Move a centre and change the radius.',predict:'How does doubling r change the number on the right of the circle equation?',a:['Radius r',.5,4,.25,2,''],b:['Centre x-coordinate h',-3,3,.5,0,''],assumption:'x and y from −8 to 8; centre y-coordinate stays zero. Both axes have the same scale.'},
 {id:'exponential',topic:'functions',title:'Growth spurt',subtitle:'A base can make all the difference.',predict:'What do bases between zero and one do as x increases?',a:['Base b',.25,2,.05,1.25,''],b:['Vertical shift q',-3,3,.5,0,''],assumption:'x from −4 to 4, y from −4 to 12. b = 1 is a constant graph, not an exponential growth or decay function.'},
 {id:'compound',topic:'finance',title:'Interest is interested',subtitle:'Compare compound growth with straight-line interest.',predict:'As time passes, why does the compound curve pull away from the straight line?',a:['Annual rate',1,20,1,8,'%'],b:['Starting amount',1000,10000,500,2000,'R'],assumption:'0 to 10 years; y shows 0 to R65,000. One initial deposit, annual compounding, no fees or withdrawals.'},
 {id:'sequence',topic:'sequences',title:'Dot by dot',subtitle:'An arithmetic pattern is a collection of points.',predict:'What changes when the common difference becomes negative?',a:['First term a',-5,5,1,1,''],b:['Common difference d',-3,3,.5,2,''],assumption:'Integer n from 1 to 10, values from −35 to 35. A sequence is discrete; the dots are not joined.'}
];
const f=n=>Number(n.toFixed(3)).toString();
function plot(fn,{xmin=-8,xmax=8,ymin=-8,ymax=8,extra=null,dots=false}={}){
 const W=420,H=320,pad=38,sx=x=>(x-xmin)/(xmax-xmin)*(W-2*pad)+pad,sy=y=>H-pad-(y-ymin)/(ymax-ymin)*(H-2*pad);
 let grid='',labels='';for(let i=0;i<=8;i++){const x=xmin+(xmax-xmin)*i/8,y=ymin+(ymax-ymin)*i/8;grid+=`<path d="M${sx(x)} ${pad}V${H-pad}M${pad} ${sy(y)}H${W-pad}" stroke="currentColor" opacity=".1"/>`;if(i%2===0)labels+=`<text x="${sx(x)}" y="${H-pad+20}" text-anchor="middle">${f(x)}</text><text x="${pad-7}" y="${sy(y)+4}" text-anchor="end">${f(y)}</text>`;}
 const curve=(fun,color)=>{let d='';for(let i=0;i<=320;i++){const x=xmin+(xmax-xmin)*i/320,y=fun(x);if(Number.isFinite(y))d+=`${i?'L':'M'}${sx(x).toFixed(2)},${sy(y).toFixed(2)} `;}return `<path d="${d}" fill="none" stroke="${color}" stroke-width="2.7"/>`};
 let drawing=dots?Array.from({length:10},(_,i)=>`<circle cx="${sx(i+1)}" cy="${sy(fn(i+1))}" r="4.5" fill="#d94979"/>`).join(''):curve(fn,'#d94979');if(extra)drawing+=curve(extra,'#3b82b6');
 return `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Interactive mathematical graph; numerical details follow below" style="color:var(--ink)"><defs><clipPath id="graph-clip"><rect x="${pad}" y="${pad}" width="${W-2*pad}" height="${H-2*pad}"/></clipPath></defs><g font-family="system-ui" font-size="12">${grid}${labels}</g>${ymin<=0&&ymax>=0?`<path d="M${pad} ${sy(0)}H${W-pad}" stroke="currentColor"/>`:''}${xmin<=0&&xmax>=0?`<path d="M${sx(0)} ${pad}V${H-pad}" stroke="currentColor"/>`:''}<g clip-path="url(#graph-clip)">${drawing}</g><text x="${W-15}" y="${H-pad+4}" fill="currentColor" font-size="13">${dots?'n':'x'}</text><text x="${pad}" y="20" fill="currentColor" font-size="13">y</text></svg>`;
}
export function simulationView(id,a,b){
 let diagram,readout,explanation;
 if(id==='parabola'){diagram=plot(x=>a*(x-b)**2);readout=`y = ${f(a)}(x − (${f(b)}))² · turning point (${f(b)}; 0)`;explanation=a===0?'At a = 0 the graph is the constant function y = 0; it is no longer a parabola.':`The graph opens ${a>0?'up':'down'}. Its minimum or maximum is at x = ${f(b)}. Increasing |a| makes it narrower.`;}
 if(id==='tangent'){const y=b*a*a,m=2*b*a;diagram=plot(x=>b*x*x,{xmin:-6,xmax:6,ymin:-6,ymax:12,extra:x=>m*(x-a)+y});readout=`f(x) = ${f(b)}x² · contact (${f(a)}; ${f(y)}) · gradient ${f(m)}`;explanation=`Pink is the curve; blue is the tangent y = ${f(m)}x + (${f(-b*a*a)}). The derivative 2ax gives the tangent gradient at each contact point.`;}
 if(id==='sine'){diagram=plot(x=>a*Math.sin(b*x*Math.PI/180),{xmin:0,xmax:720,ymin:-5,ymax:5});readout=`y = ${f(a)}sin(${f(b)}x) · amplitude ${f(Math.abs(a))} · period ${f(360/Math.abs(b))}°`;explanation='Changing a stretches the wave vertically. Changing b changes the period; a larger |b| fits more cycles into the same angle interval.';}
 if(id==='line'){diagram=plot(x=>a*x+b);readout=`y = ${f(a)}x + (${f(b)}) · gradient ${f(a)} · y-intercept (0; ${f(b)})`;explanation='The gradient is rise divided by run. The intercept is the output when x is zero. A zero gradient makes a horizontal line.';}
 if(id==='circle'){diagram=plot(x=>Math.sqrt(Math.max(0,a*a-(x-b)**2)),{extra:x=>-Math.sqrt(Math.max(0,a*a-(x-b)**2))});const points=Array.from({length:161},(_,i)=>{const t=i*2*Math.PI/160;return `${210+(b+a*Math.cos(t))*21.5},${210-a*Math.sin(t)*21.5}`}).join(' ');diagram=`<svg viewBox="0 0 420 420" role="img" aria-label="Circle centred on the horizontal axis"><path d="M38 210H382M210 38V382" stroke="currentColor"/><polyline points="${points}" fill="none" stroke="#d94979" stroke-width="3"/><circle cx="${210+b*21.5}" cy="210" r="4" fill="#3b82b6"/><text x="40" y="405" fill="currentColor">Equal axis scale · centre (${f(b)}; 0)</text></svg>`;readout=`(x − (${f(b)}))² + y² = ${f(a*a)} · radius ${f(a)}`;explanation='The constant on the right is r². Moving the centre changes the bracket on the left; it does not change the radius.';}
 if(id==='exponential'){diagram=plot(x=>a**x+b,{xmin:-4,xmax:4,ymin:-4,ymax:12});readout=`y = ${f(a)}ˣ + (${f(b)}) · y-intercept ${f(1+b)}`;explanation=a===1?'With base 1 this is a constant line. For an exponential growth or decay function, b must be positive and unequal to 1.':`This is ${a>1?'growth':'decay'} as x increases. Its horizontal asymptote is y = ${f(b)}.`;}
 if(id==='compound'){diagram=plot(x=>b*(1+a/100)**x,{xmin:0,xmax:10,ymin:0,ymax:65000,extra:x=>b*(1+a*x/100)});readout=`After 10 years: compound R${(b*(1+a/100)**10).toFixed(2)} · simple R${(b*(1+a*10/100)).toFixed(2)}`;explanation='Pink shows compound interest, blue shows simple interest. Compounding earns interest on earlier interest. The horizontal axis is years; the vertical axis is rand.';}
 if(id==='sequence'){diagram=plot(x=>a+(x-1)*b,{xmin:0,xmax:11,ymin:-35,ymax:35,dots:true});readout=`Tₙ = ${f(a)} + (n−1)(${f(b)}) · T₁₀ = ${f(a+9*b)}`;explanation='Each dot is one term at a positive integer position. The common difference changes each step by the same amount.';}
 return {diagram,readout,explanation};
}
