-- Apply after schema.sql on a new project.
create table if not exists public.qj_lessons (id text primary key,title text not null,paper integer not null check(paper in(1,2)),summary text not null,formula text not null,trap text not null,tip text not null);
alter table public.qj_lessons enable row level security;
grant select on public.qj_lessons to anon,authenticated;
grant all on public.qj_lessons to service_role;
create policy qj_lessons_read on public.qj_lessons for select to anon,authenticated using(true);
insert into public.qj_lessons(id,title,paper,summary,formula,trap,tip) values
('forces','Forces & Newton’s laws',1,'A resultant force changes velocity. Draw a free-body diagram for one object, choose axes, then add the forces along each axis. An object can move at constant velocity while the net force is zero.','ΣF = ma','Action–reaction forces act on different objects; they do not cancel on one free-body diagram.','Write a separate force equation for each object in a connected system.'),
('gravity','Universal gravitation',1,'Any two masses attract. The force becomes four times smaller when their centre-to-centre separation doubles. Gravitational field strength is force per unit mass.','F = Gm₁m₂/r²; g = GM/r²','Use the distance between centres, not just altitude above a planet.','Convert kilometres to metres before squaring the distance.'),
('momentum','Momentum & impulse',1,'Momentum is mass multiplied by velocity, so direction matters. Net impulse equals the change in momentum. Total momentum is conserved when the net external force on the system is zero.','p = mv; FnetΔt = Δp','A rebound reverses the sign of velocity. The change in momentum can exceed the initial momentum.','State the isolated-system condition before applying conservation.'),
('projectiles','Vertical projectile motion',1,'Under gravity alone, vertical acceleration is constant and downward throughout the motion, including at the highest point. At the highest point velocity is zero, not acceleration.','v = u + at; Δy = ut + ½at²','Keep your chosen positive direction consistent. A downward displacement can be negative.','Write the sign convention and use g = 9.8 m·s⁻² unless the question says otherwise.'),
('energy','Work, energy & power',1,'Work transfers energy. Only the force component parallel to displacement contributes to work. Net work equals the change in kinetic energy. Power measures the rate of energy transfer.','W = FΔx cosθ; Wnet = ΔK; P = W/Δt','Do not use conservation of mechanical energy when friction transfers mechanical energy to thermal energy.','Distinguish work by one force from net work by all forces.'),
('doppler','Doppler effect',1,'Relative motion between a sound source and listener changes the frequency heard. An approaching source compresses the wavefront spacing; a receding source spreads it out.','fL = [(v ± vL)/(v ± vS)]fS','The wave speed in the medium does not increase because the source moves.','Decide whether the heard frequency should be higher or lower before choosing signs.'),
('electrostatics','Charges & electric fields',1,'Like charges repel and unlike charges attract. Electric field direction is the direction of the force on a positive test charge. Add electric forces or fields as vectors.','F = k|q₁q₂|/r²; E = F/q','Convert microcoulombs using 10⁻⁶. Distance is squared, charge is not.','Calculate magnitudes, then explain directions using charge signs.'),
('circuits','Circuits & internal resistance',1,'Current is charge flow per second. Series components carry the same current; parallel branches share potential difference. A real cell loses some energy across its internal resistance.','V = IR; ε = I(R + r)','Terminal voltage is less than emf when a cell supplies current.','Simplify the external circuit first, then include internal resistance.'),
('machines','Generators & motors',1,'A generator converts mechanical energy into electrical energy through electromagnetic induction. A motor converts electrical energy into mechanical energy through forces on current-carrying conductors.','εavg = −NΔΦ/Δt; Φ = BA cosθ','The angle in magnetic flux is measured from the normal to the coil, not its plane.','Use the sign in Faraday’s law to explain opposition to the change, not opposition to flux itself.'),
('ac','Alternating current',1,'Alternating current changes direction. RMS values give the equivalent direct-current heating effect in a resistor. For a sinusoidal supply, RMS is peak divided by √2.','Vrms = Vmax/√2; Irms = Imax/√2','Use RMS values for average power in a resistor, not peak values.','State that the peak-to-RMS relation assumes a sinusoidal waveform.'),
('photoelectric','Photoelectric effect & spectra',1,'A photon transfers a discrete energy hf. Electrons are emitted only if photon energy reaches the work function. Above threshold, higher frequency increases maximum kinetic energy; greater intensity increases photon arrival rate.','E = hf; Kmax = hf − W₀','Increasing intensity below threshold does not release electrons in this model.','Convert wavelength to metres and use f = c/λ before calculating photon energy.'),
('organic-names','Organic names & groups',2,'Identify the functional group first. Find a suitable longest carbon chain, number it to give the functional group the lowest permitted locant, and then name branches and unsaturation.','Alkane: CₙH₂ₙ₊₂; alkene: CₙH₂ₙ','A molecular formula alone may represent more than one structural isomer.','Show functional groups clearly when drawing structural formulae.'),
('organic-properties','Organic properties',2,'Boiling point depends on the energy required to overcome intermolecular forces. Compare hydrogen bonding, dipole interactions and London forces while controlling for size and shape.','Stronger intermolecular attraction → higher boiling point','Boiling overcomes intermolecular forces, not the covalent bonds within each molecule.','Link structure → intermolecular forces → energy needed → boiling point.'),
('organic-reactions','Organic reactions & polymers',2,'Use the functional group to identify possible reaction pathways. Addition can consume a double bond; elimination can create one. Esterification combines an alcohol and carboxylic acid under suitable conditions.','Alcohol + carboxylic acid ⇌ ester + water','State reagents and conditions; naming only the reaction often misses marks.','Track carbon atoms through the reaction and distinguish substitution from addition.'),
('rates','Reaction rates & energy',2,'Reaction rate describes change in concentration or amount per time. Higher temperature increases the fraction of collisions with enough energy. A catalyst offers a pathway with lower activation energy.','Rate = |Δc|/Δt; ΔH = Hproducts − Hreactants','A catalyst changes neither ΔH nor the equilibrium constant at a fixed temperature.','For temperature explanations, mention both collision frequency and sufficient collision energy.'),
('equilibrium','Chemical equilibrium',2,'In a closed system at equilibrium, forward and reverse reaction rates are equal. Concentrations stay constant but need not be equal. Only temperature changes Kc for a given reaction.','Kc = products / reactants, each raised to stoichiometric powers','Exclude pure solids and liquids from the concentration expression.','Use a change table; distinguish a concentration change from a temperature change.'),
('acids','Acids, bases & pH',2,'A Brønsted–Lowry acid donates a proton and a base accepts one. Strong acids ionise extensively; concentration describes how much solute is present per volume and is a different idea.','pH = −log[H₃O⁺]; Kw = [H₃O⁺][OH⁻]','Strong does not mean concentrated. Use Kw = 1.0 × 10⁻¹⁴ only at 25 °C.','Check whether complete ionisation is justified before equating acid concentration and hydronium concentration.'),
('titrations','Titrations & stoichiometry',2,'At equivalence, the reacting amounts follow the balanced equation. Convert volumes to dm³, calculate moles, use the coefficient ratio, then find the unknown concentration.','n = cV; nA/a = nB/b','The endpoint is an observed indicator change; the equivalence point is the stoichiometric condition.','Use the balanced equation; not every titration has a 1:1 ratio.'),
('galvanic','Galvanic cells & redox',2,'Spontaneous redox reactions can supply electrical energy. Oxidation occurs at the anode and reduction at the cathode. In a galvanic cell electrons flow externally from negative anode to positive cathode.','E°cell = E°cathode − E°anode','Use reduction potentials for both half-cells; do not multiply electrode potentials by coefficients.','A salt bridge conducts ions, not electrons, to maintain electrical neutrality.'),
('electrolysis','Electrolytic cells',2,'An external power supply drives a nonspontaneous redox reaction. Oxidation is still at the anode and reduction at the cathode, but in an electrolytic cell the anode is positive and the cathode negative.','Oxidation: electrons lost; reduction: electrons gained','Products depend on the electrolyte, concentration and electrode material. Aqueous and molten salts can behave differently.','For refining, distinguish the impure anode from the pure-metal cathode.')
on conflict(id) do update set title=excluded.title,paper=excluded.paper,summary=excluded.summary,formula=excluded.formula,trap=excluded.trap,tip=excluded.tip;
