export const simulations=[
{id:'forces',title:'Give it a nudge',topic:'forces',subtitle:'How force and mass change acceleration.',a:['Net force',1,100,1,25,'N'],b:['Mass',1,20,1,5,'kg'],assumption:'A constant horizontal net force; the displayed force already includes any friction.',predict:'Keep the force fixed. What happens to acceleration if you double the mass?'},
{id:'projectile',title:'What goes up…',topic:'projectiles',subtitle:'A vertical throw, frozen at any moment.',a:['Launch speed',5,30,1,20,'m·s⁻¹'],b:['Time after launch',0,6,.1,1,'s'],assumption:'Vertical motion, no air resistance, g = 9.8 m·s⁻². The launch level is the ground.',predict:'At the highest point, which is zero: velocity or acceleration?'},
{id:'energy',title:'Energy, on the move',topic:'energy',subtitle:'Turn height into motion without losing energy.',a:['Initial height',1,20,1,10,'m'],b:['Height remaining',0,100,1,50,'%'],assumption:'Starts from rest. No friction or air resistance. Mass = 1 kg; total mechanical energy stays constant.',predict:'At half the starting height, is the speed half the final speed?'},
{id:'circuit',title:'A little resistance',topic:'circuits',subtitle:'See why real cells lose some voltage.',a:['Cell emf',1,24,.5,12,'V'],b:['External resistance',1,30,.5,6,'Ω'],assumption:'One ohmic external resistor and fixed internal resistance r = 1 Ω.',predict:'If external resistance decreases, what happens to current and lost volts?'},
{id:'doppler',title:'Hear the difference',topic:'doppler',subtitle:'A siren approaches a stationary listener.',a:['Source frequency',200,1000,10,500,'Hz'],b:['Approach speed',0,100,1,30,'m·s⁻¹'],assumption:'Stationary listener; source approaches through still air. Sound speed = 340 m·s⁻¹.',predict:'Does the siren itself change its emitted frequency when it approaches?'},
{id:'photoelectric',title:'A photon’s permission slip',topic:'photoelectric',subtitle:'Frequency decides whether electrons can escape.',a:['Frequency',2,12,.1,6,'× 10¹⁴ Hz'],b:['Work function',1,5,.1,2,'× 10⁻¹⁹ J'],assumption:'Single-photon photoelectric model; h = 6.63 × 10⁻³⁴ J·s. Intensity is held fixed.',predict:'Can brighter light eject electrons if its frequency is below the threshold?'},
{id:'rates',title:'Climb the energy hill',topic:'rates',subtitle:'A catalyst provides a lower-energy pathway.',a:['Uncatalysed activation energy',50,120,1,90,'kJ·mol⁻¹'],b:['Catalyst reduction',0,40,1,25,'kJ·mol⁻¹'],assumption:'Schematic exothermic reaction. Reactant energy = 40; product energy = 10 kJ·mol⁻¹. Not a measured rate curve.',predict:'Does a catalyst change the energy difference between products and reactants?'},
{id:'equilibrium',title:'Balance, not stillness',topic:'equilibrium',subtitle:'Explore an ideal A ⇌ B equilibrium.',a:['Equilibrium constant Kc',.1,10,.1,2,''],b:['Total concentration',.2,2,.1,1,'mol·dm⁻³'],assumption:'Illustrative 1:1 closed-system reaction with ideal concentrations. Kc is a parameter representing a chosen temperature, not a concentration-driven change.',predict:'Can a system be at equilibrium when product and reactant concentrations differ?'},
{id:'ph',title:'One small pH step',topic:'acids',subtitle:'A logarithmic scale with a big concentration change.',a:['pH',1,13,.1,3,''],b:['Sample volume',10,1000,10,100,'cm³'],assumption:'Ideal dilute aqueous solution at 25 °C; Kw = 1.0 × 10⁻¹⁴. Changing volume here selects a larger sample of the same solution, not a dilution.',predict:'When pH falls by one, what happens to hydronium concentration?'},
{id:'cell',title:'Follow the electrons',topic:'galvanic',subtitle:'A zinc–copper cell supplies an external load.',a:['Current',.1,2,.1,.5,'A'],b:['Time',10,300,10,60,'s'],assumption:'Standard Zn/Cu cell, ideal emf 1.10 V. Current is an illustrative circuit condition; it is not calculated from electrode area.',predict:'Why do electrons travel through the wire rather than through the salt bridge?'}
];
const fmt=n=>Math.abs(n)<.001&&n!==0?n.toExponential(2):Number(n.toFixed(3));
const svg=body=>`<svg viewBox="0 0 600 270" role="img" aria-label="Interactive science model"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="#c35227"/></marker></defs>${body}</svg>`;
export function simulationView(id,a,b){
let diagram='',readout='',explanation='';
switch(id){
case 'forces':{const acc=a/b;diagram=`<path d="M50 220H550" stroke="#71816b" stroke-width="2"/><rect x="190" y="125" width="120" height="95" rx="10" fill="#e2d9f2" stroke="#25332e"/><text x="250" y="178" text-anchor="middle">${b} kg</text><path d="M315 170h${Math.min(a*1.9,210)}" stroke="#c35227" stroke-width="4" marker-end="url(#arrow)"/><text x="350" y="140">Fnet = ${a} N</text><text x="80" y="50">More net force → more acceleration</text>`;readout=`a = ${a}/${b} = ${fmt(acc)} m·s⁻²`;explanation='The net force changes velocity. Increasing mass at the same net force reduces acceleration. The drawing shows the net force, not a complete free-body diagram.';break;}
case 'projectile':{const flight=2*a/9.8,t=Math.min(b,flight),y=Math.max(0,a*t-4.9*t*t),v=a-9.8*t,max=a*a/19.6,cy=225-y/Math.max(max,1)*175;diagram=`<path d="M90 230H510" stroke="#71816b" stroke-width="2"/><path d="M300 45V225" stroke="#aaa" stroke-dasharray="5 5"/><circle cx="300" cy="${cy}" r="15" fill="#e97743"/><text x="335" y="${Math.max(cy,40)}">${fmt(y)} m</text><text x="50" y="40">Acceleration: 9.8 m·s⁻² downward</text><text x="50" y="65">Highest point: ${fmt(a/9.8)} s</text>`;readout=`Height ${fmt(y)} m · Velocity ${b>flight?'landed':fmt(v)+' m·s⁻¹'} · Flight ${fmt(flight)} s`;explanation=b>flight?'The ball has reached the ground. This model stops at the first landing.':'Upward is positive. As the ball rises its upward velocity decreases; downward acceleration remains constant.';break;}
case 'energy':{const total=9.8*a,U=total*b/100,K=total-U,v=Math.sqrt(2*K);diagram=`<rect x="105" y="${220-160*b/100}" width="85" height="${160*b/100}" rx="5" fill="#b3c59a"/><rect x="255" y="${220-160*(1-b/100)}" width="85" height="${160*(1-b/100)}" rx="5" fill="#ef9b70"/><rect x="405" y="60" width="85" height="160" rx="5" fill="#b8a4d7"/><text x="147" y="245" text-anchor="middle">Potential</text><text x="297" y="245" text-anchor="middle">Kinetic</text><text x="447" y="245" text-anchor="middle">Total</text>`;readout=`U = ${fmt(U)} J · K = ${fmt(K)} J · Speed = ${fmt(v)} m·s⁻¹`;explanation='As height decreases, gravitational potential energy becomes kinetic energy. Total mechanical energy stays constant for this frictionless model.';break;}
case 'circuit':{const I=a/(b+1),terminal=I*b;diagram=`<path d="M140 90H245M350 90H460V210H140V90" fill="none" stroke="#25332e" stroke-width="3"/><path d="M255 65V115M270 76V104M305 80l8 20 8-20 8 20 8-20" stroke="#c35227" stroke-width="3" fill="none"/><rect x="260" y="196" width="80" height="28" fill="#e2d9f2" stroke="#25332e"/><text x="265" y="45">${a} V emf</text><text x="306" y="135">r = 1 Ω</text><text x="267" y="250">R = ${b} Ω</text><text x="35" y="160">${fmt(I)} A</text>`;readout=`I = ${fmt(I)} A · Terminal V = ${fmt(terminal)} V · Lost volts = ${fmt(I)} V`;explanation='Internal resistance shares the emf with the external resistor. Higher current causes a larger internal voltage drop.';break;}
case 'doppler':{const heard=340*a/(340-b),spacing=35*(340-b)/340;diagram=`${[1,2,3,4].map(k=>`<circle cx="210" cy="140" r="${k*spacing}" fill="none" stroke="#b4c5a8" stroke-width="2"/>`).join('')}<circle cx="210" cy="140" r="16" fill="#e97743"/><path d="M235 140H285" stroke="#c35227" stroke-width="3" marker-end="url(#arrow)"/><circle cx="500" cy="140" r="20" fill="#b7a2d6"/><text x="460" y="195">Listener</text><text x="160" y="245">Wave spacing ahead (schematic)</text>`;readout=`Emitted ${a} Hz · Heard ${fmt(heard)} Hz · λahead = ${fmt((340-b)/a)} m`;explanation='The approaching source shortens wavefront spacing ahead. The listener hears a higher frequency while sound speed in the air stays the same.';break;}
case 'photoelectric':{const E=6.63e-34*a*1e14,W=b*1e-19,K=Math.max(0,E-W),emit=E>=W;diagram=`<rect x="330" y="80" width="35" height="150" fill="#b7a2d6"/><path d="M90 100q15-25 30 0t30 0t30 0t30 0t30 0h75" stroke="#c35227" fill="none" stroke-width="3" marker-end="url(#arrow)"/><text x="90" y="65">Photon: ${fmt(E/1e-19)} × 10⁻¹⁹ J</text>${emit?'<circle cx="465" cy="125" r="8" fill="#c35227"/><path d="M380 130H450" stroke="#c35227" stroke-width="2" marker-end="url(#arrow)"/>':'<text x="390" y="145">No emission</text>'}<text x="270" y="255">Metal surface</text>`;readout=`${emit?'Emission':'No emission'} · Kmax = ${fmt(K)} J · f₀ = ${fmt(W/6.63e-34)} Hz`;explanation=emit?'The photon has enough energy to remove an electron. Energy left after the work function becomes maximum kinetic energy.':'Photon energy is below the work function. Greater intensity at this frequency does not produce emission in the single-photon model.';break;}
case 'rates':{const peak=185-a,cat=peak+b;diagram=`<path d="M60 235V30M60 235H560" stroke="#71816b" fill="none"/><path d="M75 175H145C220 175 205 ${peak} 295 ${peak}S375 215 450 215H540" stroke="#c35227" stroke-width="3" fill="none"/><path d="M75 175H145C220 175 205 ${cat} 295 ${cat}S375 215 450 215H540" stroke="#9f87c7" stroke-width="3" fill="none" stroke-dasharray="7 5"/><text x="90" y="160">Reactants</text><text x="435" y="200">Products</text><text x="235" y="260">Reaction progress</text><text x="75" y="30">Energy (schematic)</text>`;readout=`Ea without catalyst = ${a} · Ea with catalyst = ${a-b} kJ·mol⁻¹ · ΔH = −30 kJ·mol⁻¹`;explanation='The catalyst lowers the activation barrier. The starting and finishing energies are unchanged, so ΔH is unchanged.';break;}
case 'equilibrium':{const A=b/(1+a),B=b-A;diagram=`<rect x="110" y="55" width="140" height="165" rx="12" fill="#e6edde"/><rect x="350" y="55" width="140" height="165" rx="12" fill="#e9e4f6"/>${Array.from({length:Math.round(A/b*24)},(_,i)=>`<circle cx="${128+i%5*24}" cy="${78+Math.floor(i/5)*28}" r="6" fill="#647d50"/>`).join('')}${Array.from({length:Math.round(B/b*24)},(_,i)=>`<circle cx="${368+i%5*24}" cy="${78+Math.floor(i/5)*28}" r="6" fill="#9071bb"/>`).join('')}<text x="283" y="135" font-size="30">⇌</text><text x="170" y="246">A</text><text x="411" y="246">B</text>`;readout=`[A] = ${fmt(A)} · [B] = ${fmt(B)} mol·dm⁻³ · Kc = [B]/[A] = ${a}`;explanation='Equilibrium requires equal forward and reverse rates, not equal concentrations. Here Kc fixes the concentration ratio and total concentration fixes the scale.';break;}
case 'ph':{const H=10**(-a),OH=1e-14/H;diagram=`<defs><linearGradient id="ph"><stop stop-color="#de7258"/><stop offset=".5" stop-color="#aacb9a"/><stop offset="1" stop-color="#9383c6"/></linearGradient></defs><rect x="60" y="125" width="480" height="40" rx="20" fill="url(#ph)"/><path d="M${60+(a-1)/12*480} 100v85" stroke="#25332e" stroke-width="3"/><text x="60" y="210">Acidic</text><text x="270" y="210">Neutral</text><text x="495" y="210">Basic</text><text x="230" y="65">pH ${a} at 25 °C</text>`;readout=`[H₃O⁺] = ${fmt(H)} M · [OH⁻] = ${fmt(OH)} M · H₃O⁺ in sample = ${fmt(H*b/1000)} mol`;explanation='The pH scale is logarithmic. Moving down one pH unit multiplies hydronium concentration by ten. Sample volume affects the amount, not this solution’s concentration.';break;}
case 'cell':{diagram=`<path d="M100 125v100h150V125M350 125v100h150V125" fill="none" stroke="#71816b" stroke-width="3"/><path d="M200 175V100Q300 20 400 100V175" fill="none" stroke="#b5a3d4" stroke-width="12"/><rect x="125" y="100" width="17" height="105" fill="#aab4af"/><rect x="455" y="100" width="17" height="105" fill="#d78b66"/><path d="M133 100V40H463V100" fill="none" stroke="#25332e" stroke-width="3"/><path d="M235 40H360" stroke="#c35227" stroke-width="3" marker-end="url(#arrow)"/><text x="245" y="25">electrons →</text><text x="82" y="253">Zn anode (−)</text><text x="398" y="253">Cu cathode (+)</text>`;readout=`Standard emf = 1.10 V · Charge passed = ${fmt(a*b)} C`;explanation='Zinc is oxidised: Zn → Zn²⁺ + 2e⁻. Copper ions are reduced: Cu²⁺ + 2e⁻ → Cu. The salt bridge completes the internal ionic circuit.';break;}
}
return{diagram:svg(diagram),readout,explanation};
}
